In [211]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)

In [212]:
df = pd.read_csv('csv/Task1-Var13.csv')
x = df.to_numpy()
print("Выборка (вариант 13) \n", x)

Выборка (вариант 13) 
 [[ 2.064  0.94   4.928  0.943  3.695  5.482  0.705  0.939  1.396  2.415]
 [ 1.395  0.146  1.64   1.997  0.041  1.548  2.209  1.059  0.232  0.039]
 [ 0.466  1.32   0.241  2.868  4.77   2.482  1.023  1.389  0.222  2.169]
 [ 5.375  1.608  1.941  1.464  1.208  1.542  0.619  1.906  0.741  2.604]
 [ 6.927  1.79   4.381  0.043  1.503  0.417  2.303  1.537 10.921  2.087]
 [ 9.411  3.633  2.254  2.814  0.497  3.044  2.832  1.367  3.648  9.483]
 [ 1.668  0.828  5.557  6.035  1.171  0.333  1.104  2.632  0.58   2.676]
 [ 3.604  0.823  1.396  7.921  3.041  2.261  0.233  2.1    0.026  0.36 ]
 [ 2.939  3.2    0.234  5.611  6.665  3.222  3.233  2.51   1.78   0.028]
 [ 4.649  0.577  0.472  0.13   4.305  1.198  5.612  2.77   0.132  0.18 ]
 [ 5.663  1.774  1.097  0.305  1.638  6.714  0.088  3.123  0.149  5.202]
 [ 0.401  9.007  0.148  1.748  6.172  2.424  1.253  0.33   2.136  2.776]
 [ 0.231  1.896  2.424  0.659  0.116  9.778  0.43   4.015  1.162  0.651]
 [ 0.23   0.514  7.561  5.95

In [213]:
# Задание 1 (Найдите крайние члены вариационного ряда и размах выборки)

n = x.size
Max = np.amax(x)
Min = np.amin(x)
w = Max - Min

print("Размер n = %d\nКрайние члены вариационного ряда max = %.3f, min = %.5f\nРазмах выборки w = %f" 
      %(n, Max, Min, w))

Размер n = 150
Крайние члены вариационного ряда max = 10.921, min = 0.00621
Размах выборки w = 10.914790


In [219]:
# Задание 2 (Осуществите группировку данных)
l = math.trunc(1 + math.log2(n))
h = w / l

print("Число интервалов l = %d\nШаг(ширина интервалов группировки) h = %f" %(l, h))

hist, bin_edges = np.histogram(x, l)
bin_edges_average = np.zeros(bin_edges[:8].size)
for i in range (l):
    bin_edges_average[i] = (bin_edges[i] + bin_edges[i + 1]) / 2 
f = pd.Series(data=hist, index=bin_edges_average)

print("\n")
print("Cредние значения каждого из  интервалов (первый столбец)\nЧастоты попадания элементов в каждый из интервалов(второй столбец)")
print(f.to_string())

p = pd.Series(data=hist / n, index=bin_edges_average)
print("\n")
print("Относительные частоты ")
print(p.to_string(index=False))

Int = bin_edges_average

Число интервалов l = 8
Шаг(ширина интервалов группировки) h = 1.364349


Cредние значения каждого из  интервалов (первый столбец)
Частоты попадания элементов в каждый из интервалов(второй столбец)
0.688384     64
2.052733     42
3.417082     19
4.781431      7
6.145779     10
7.510128      3
8.874477      3
10.238826     2


Границы интервалов
[ 0.006  1.371  2.735  4.099  5.464  6.828  8.192  9.557 10.921]


In [215]:
# Задание 3 (По сгруппированным данным постройте гистограмму относительных частот)

plt.figure(figsize=(10,6))
x = histogram['l']
y = histogram['f1']
plt.bar(x, y, width=h)
plt.plot(x, y, color = 'black')
plt.show()